apiVersion: batch/v1
kind: Job
metadata:
  name: seeding
spec:
  template:
    spec:
      containers:
      - name: seeding
        image: 'nyuappsec/seeding:v0'
        command: ["/bin/sh"]
        args: ["-c","mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --database=${MYSQL_DATABASE} --host=mysql-service -f < /docker-entrypoint-initdb.d/seedjob.sql"]
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-part-1a
                key: password

          - name:  MYSQL_DATABASE
            value: GiftcardSiteDB

         command: ["mysqld",  "/seed.sql"]
      restartPolicy: Never
  backoffLimit: 10